trigger:
  - master

resources:
  - repo: self

variables:
  CONTAINER_REGISTRY: 'evspyacrtest'
  CONFIG_PORT: '8888'
  EVENTMANAGER_PORT: '9999'
  vmImageName: 'ubuntu-latest'
  IMAGE_TAG: '$(Build.BuildId)'


stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build and Push Container Images
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureKeyVault@1
            displayName: Fetch secrets from Azure Key vault
            inputs:
              azureSubscription: 'servconn'
              KeyVaultName: 'evspykv'
              SecretsFilter: '*'

          - task: Bash@3
            displayName: Build container images for each service
            inputs:
              azureSubscription: 'servconn'
              targetType: 'inline'
              script: |
                export CONTAINER_REGISTRY=$(CONTAINER_REGISTRY)
                export IMAGE_TAG=$(IMAGE_TAG)
                echo 'Install ACR AAD credential helper and login'

                az login
                curl -L https://aka.ms/acr/installaad/bash | /bin/bash
                az acr login -n $(CONTAINER_REGISTRY)
                docker login -u $(AZURE-REGISTRY-USERNAME) -p $(AZURE-REGISTRY-PASSWORD) $(CONTAINER_REGISTRY).azurecr.io

                echo 'Start Build'

                cd eventmanager
                mvn compile jib:build \
                  -Djib.container.environment=KV_CLIENT_ID=$(KV-CLIENT-ID);KV_CLIENT_KEY=$(KV-CLIENT-KEY);KV_TENANT_ID=$(KV-TENANT-ID)

                echo 'Build complete'

          - publish: kubernetes
            artifact: kubernetes

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build

    jobs:
      - deployment: Deploy
        displayName: Deploy to AKS
        pool:
          vmImage: $(vmImageName)
        environment: 'Eventspy.default'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureKeyVault@1
                  displayName: Fetch secrets from Azure Key vault
                  inputs:
                    azureSubscription: 'servconn'
                    KeyVaultName: 'evspykv'
                    SecretsFilter: '*'
                - task: replacetokens@3
                  displayName: Replace CONTAINER_REGISTRY & IMAGE_TAG in all the manifest files
                  inputs:
                    targetFiles: '$(Pipeline.Workspace)/kubernetes/*.yaml'
                    tokenPrefix: '${'
                    tokenSuffix: '}'

                - task: KubernetesManifest@0
                  displayName: Create generic secrets to be available on pods
                  inputs:
                    action: 'createSecret'
                    secretType: 'generic'
                    secretName: 'evspykv'
                    secretArguments: '--from-literal=kv_client_id=$(KV-CLIENT-ID) --from-literal=kv_client_key=$(KV-CLIENT-KEY) --from-literal=tenant_id=$(TENANT-ID)'


                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    azureSubscription: 'servconn'
                    action: deploy
                    manifests: |
                      $(Pipeline.Workspace)/kubernetes/2-eventmanager.yaml
