azure:
  maps:
    live:
      enabled: true
  keyvault:
    enabled: true
    uri: https://settings-kv.vault.azure.net/
    client-id: ${KV_CLIENT_ID}
    client-key: ${KV_CLIENT_KEY}
    tenant-id: ${KV_TENANT_ID}

    secret:
      keys: azureMapsUrl,azureMapsSubscription,eventGridEndpoint,eventGridKey,serviceBusConnStr,queNameSpace,mlScoreUrl
  activedirectory:
    tenant-id: a0180a5d-f614-46af-af02-0877860375b4
    active-directory-groups: users

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: a2e97953-ec51-4bad-807f-99d8d84dd1d3
            client-secret: q_yL6.yC1EYZ18tt4KpdlXEq9O__aelLcH
  data:
    mongodb:
      database: eventspydb
      uri: mongodb://eventspydb:lXL8XflWPt6Eqkl0PXpSbgxbvkIOLRdvqCvHaYIvyHzdJvR11DuhYRn7txdLqSmTvT8UacWXBkZV42SmUV6ctQ==@eventspydb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@eventspydb@

server:
  port: 9999
