---
apiVersion: v1
kind: Service
metadata:
  labels:
    project: eventspy
    tier: backend
    app: eventmanager
  name: eventmanager
spec:
  ports:
  - name: http
    port: 6000
    targetPort: 6000
  selector:
    project: eventspy
    tier: backend
    app: eventmanager
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: eventspy
    tier: backend
    app: eventmanager
  name: eventmanager
spec:
  selector:
    matchLabels:
      app: eventmanager
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: eventspy
        tier: backend
        app: eventmanager
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - env:
        - name: CONNECTION_STRING
        ports:
        - containerPort: 80
        image: ${CONTAINER_REGISTRY}.azurecr.io/eventspy-eventmanager:${IMAGE_TAG}
        name: eventmanager
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: eventmanager
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: eventmanager
